
-- Dabase Aula12
CREATE DATABASE AULA12;

-- Seta Aula12
USE AULA12;

-- Table Categoria
CREATE TABLE CATEGORIA
( IDCA INT AUTO_INCREMENT,
  NOME VARCHAR(50) NOT NULL,
  PRIMARY KEY(IDCA));

-- Table Produto
CREATE TABLE PRODUTO
( IDPR INT AUTO_INCREMENT,
  NOME VARCHAR(150) NOT NULL,
  PRECO DOUBLE(9,2) NOT NULL,
  QUANTIDADE INT NOT NULL,
  CATEGORIA INT NOT NULL,
  PRIMARY KEY(IDPR));

-- Relacionamento Categorias X Produto
ALTER TABLE PRODUTO 
ADD FOREIGN KEY (CATEGORIA) REFERENCES CATEGORIA (IDCA);

-- Insert Categoria
INSERT INTO CATEGORIA (NOME) 
     VALUES ('LIVROS'),
			('JOGOS'),
            ('FILMES'),
			('REVISTAS');

-- Select Categoria
SELECT * FROM CATEGORIA;
SELECT IDCA,CATEGORIA FROM CATEGORIA;

-- Insert Produto
INSERT INTO PRODUTO (NOME, PRECO, QUANTIDADE, CATEGORIA) 
     VALUES ('O SENHOR DOS ANÉIS, TRILOGIA COMPLETA', 119.50, 10, 3),
            ('BATMAN ARKAHAN CITY', 65.99, 7, 2), 
            ('JOGADOR Nº 1', 29.90, 5, 1),
            ('AS CRONICAS DE GELO E FOGO - 5 LIVROS', 199.99, 2, 1),
            ('O PODEROSO CHEFÃO', 89.90, 1, 3);

-- Select Produto
SELECT * FROM PRODUTO;
